<?php

    namespace Database\Seeders;

    use App\Models\Currency;
    use App\Models\Language;
    use App\Models\Translation;
    use App\Models\TranslationKey;
    use App\Models\User;
    // use Illuminate\Database\Console\Seeds\WithoutModelEvents;
    use Illuminate\Database\Seeder;
    use Illuminate\Support\Facades\Http;

    class DatabaseSeeder extends Seeder
    {
        /**
         * Seed the application's database.
         */
        protected $keys = [
            "website.navigator.home" => "Text for the home navigation menu item",
            "website.navigator.cars" => "Text for the cars navigation menu item",
            "website.navigator.locations" => "Text for the locations navigation menu item",
            "website.navigator.campaigns" => "Text for the campaigns navigation menu item",
            "website.navigator.car_porte_car_rental" => "Brand name for the car rental service",
            "website.navigator.about_us" => "Text for the about us navigation menu item",
            "website.navigator.check_reservation" => "Text for the check reservation menu item",
            "website.navigator.blog" => "Text for the blog menu item",

            "website.car_card.properties.properties_label" => "CarGroup Card Properties label",
            "website.car_card.properties.seat_count_{count}" => "CarGroup Card Properties seat count",
            "website.car_card.properties.trunk_capacity_{trunk_capacity}" => "CarGroup Card Properties trunk capacity",
            "website.car_card.requirements.requirements_label" => "CarGroup Card Requirements label",
            "website.car_card.requirements.required_min_{age}" => "Minimum age requirement with dynamic age parameter",
            "website.car_card.requirements.{year}_year_experience" => "Years of experience requirement with dynamic year parameter",
            "website.car_card.requirement.{amount}_{currency}_deposit" => "Deposit amount with dynamic currency and amount parameters",

            "website.car.transmission_type" => "Label for transmission type selection",
            "website.car.fuel_type" => "Label for fuel type selection",
            "website.car.segment" => "Label for vehicle segment/category",
            "website.car.body_type" => "Label for vehicle body type",
            "website.car.trunk_capacity" => "Label for trunk capacity information",
            "website.car.seat_count" => "Label for seat count",
            "website.car.car_properties" => "Heading for car properties section",
            "website.car.requirement.deposit" => "Label for deposit requirement",
            "website.car.requirement.experience" => "Label for driving experience requirement",
            "website.car.requirements.requirements_label" => "Heading for requirements section",
            "website.car.requirements.required_min_age" => "Minimum age requirement with dynamic age parameter",
            "website.car.requirements.experience" => "Years of experience requirement with dynamic year parameter",
            "website.car.requirements.deposit" => "Deposit amount with dynamic currency and amount parameters",
            "website.car.services_included_for_this_vehicle" => "Heading for included services section",
            "website.car.options_and_extras" => "Heading for options and extras section",

            "website.searchReservation.filter.sort.sort_label" => "Label for sort filter dropdown",
            "website.searchReservation.filter.sort.price_increase" => "Option for price low to high sorting",
            "website.searchReservation.filter.sort.price_decrease" => "Option for price high to low sorting",
            "website.searchReservation.filter.fuel_type_label" => "Label for fuel type filter",
            "website.searchReservation.filter.segments_label" => "Label for segment filter",
            "website.searchReservation.filter.transmission_type_label" => "Label for transmission type filter",
            "website.searchReservation.rent_now" => "Label for renting now",

            "website.auth.login.login_label" => "Login form heading",
            "website.auth.login.email_label" => "Email input field label",
            "website.auth.login.invalid_email" => "Error message for invalid email format",
            "website.auth.login.password_label" => "Password input field label",
            "website.auth.login.he_password_must_be_at_least_6_characters_long" => "Password length requirement error message",
            "website.auth.login.button.save" => "Login button text",


            "website.auth.signup.name" => "First name input field label",
            "website.auth.signup.surname" => "Last name input field label",
            "website.auth.signup.email" => "Email input field label for signup",
            "website.auth.signup.birthday" => "Birthday input field label",
            "website.auth.signup.phone_number" => "Phone number input field label",
            "website.auth.signup.identity_number" => "TC identification number input field label",
            "website.auth.signup.password" => "Password input field label",
            "website.auth.signup.password_confirmation" => "Password confirmation input field label",
            "website.auth.signup.this_area_cannot_be_empty" => "Error message for required fields",
            "website.auth.signup.passwords_do_not_match" => "Error message for password mismatch",
            "website.auth.signup.you_can_enter_only_number" => "You can enter only number",
            "website.auth.signup.invalid_email" => "Error message for invalid email in signup",
            "website.auth.signup.he_password_must_be_at_least_6_characters_long" => "Password length requirement for signup",
            "website.auth.signup.signup_label" => "Signup button text",
            "website.auth.signup.button.save" => "Signup button text",

            "website.home.pick_up_location" => "Label for pickup location selector",
            "website.home.return_location" => "Label for return location selector",
            "website.home.pick_up_date_and_time" => "Label for pickup date/time selector",
            "website.home.return_date_and_time" => "Label for return date/time selector",
            "website.home.button.save" => "Text for search button",

            "adminpanel.navigator.home" => "adminpanel Home label",
            "adminpanel.navigator.vehicle" => "Admin menu item for single vehicle",
            "adminpanel.navigator.vehicles" => "Admin menu item for vehicles section",
            "adminpanel.navigator.add_vehicles" => "Admin menu item for adding vehicles",
            "adminpanel.navigator.reservation" => "Admin menu item for single reservation",
            "adminpanel.navigator.reservations" => "Admin menu item for reservations section",
            "adminpanel.navigator.pricing" => "Admin menu item for pricing section",
            "adminpanel.navigator.drop_price" => "Admin menu item for dynamic pricing",
            "adminpanel.navigator.discounts" => "Admin menu item for discounts management",
            "adminpanel.navigator.add_discount" => "Admin menu item for adding discounts",
            "adminpanel.navigator.extra_services" => "Admin menu item for extra services",
            "adminpanel.navigator.internal_services" => "Admin menu item for internal services",
            "adminpanel.navigator.external_services" => "Admin menu item for external services",
            "adminpanel.navigator.campaigns" => "Admin menu item for campaigns",
            "adminpanel.navigator.add_campaign" => "Admin menu item for adding campaigns",
            "adminpanel.navigator.locations" => "Admin menu item for locations management",
            "adminpanel.navigator.users" => "Admin menu item for user management",
            "adminpanel.navigator.language_operations" => "Admin menu item for language operations",
            "adminpanel.navigator.add_language" => "Admin menu item for adding languages",
            "adminpanel.navigator.car_properties" => "Admin menu item for cars properties",
            "adminpanel.navigator.segments" => "Admin menu item for cars segments",
            "adminpanel.navigator.add_segment" => "Admin menu item for add cars segments",
            "adminpanel.navigator.body_types" => "Admin menu item for cars boy types",
            "adminpanel.navigator.add_body_type" => "Admin menu item for add cars body types",
            "adminpanel.navigator.fuels" => "Admin menu item for cars fuels",
            "adminpanel.navigator.add_fuel" => "Admin menu item for add cars fuels",
            "adminpanel.navigator.transmissions" => "Admin menu item for cars transmissions",
            "adminpanel.navigator.add_transmission" => "Admin menu item for add cars transmissions",
            "adminpanel.navigator.email_templates" => "Admin menu item for email templates",
            "adminpanel.navigator.add_car_group" => "Admin menu item for add cars group",
            "adminpanel.navigator.car_groups" => "Admin menu item for cars groups",
            "adminpanel.navigator.website" => "Admin menu item for website",
            "adminpanel.navigator.website_settings" => "Admin menu item for website settings",
            "adminpanel.navigator.page_settings" => "Admin menu item for page settings",
            "adminpanel.navigator.about_page" => "Admin menu item for about page settings",
            "adminpanel.navigator.blog_page" => "Admin menu item for blog page settings",
            "adminpanel.navigator.blog_page_add" => "Admin menu item for blog add page settings",
            "adminpanel.navigator.navigation_bar_settings" => "Admin menu item for navigation bar settings",
            // Email Templates
            "adminpanel.email.edit_email_template" => "Edit Email Template",
            "adminpanel.email.back" => "Back",
            "adminpanel.email.template_name" => "Template Name",
            "adminpanel.email.template_name_placeholder" => "e.g., password_reset",
            "adminpanel.email.subject" => "Subject",
            "adminpanel.email.email_subject_placeholder" => "Email subject (use {{variables}} for dynamic content)",
            "adminpanel.email.email_subject_input" => "Email subject",
            "adminpanel.email.body" => "Body",
            "adminpanel.email.email_body_placeholder" => "Use {{variable}} placeholders for dynamic content.",
            "adminpanel.email.update_template" => "Update Template",
            "adminpanel.email.cancel" => "Cancel",
            "adminpanel.email.email_templates" => "Email Templates",
            "adminpanel.email.add_template" => "Add Template",
            "adminpanel.email.search_templates" => "Search templates...",
            "adminpanel.email.name" => "Name",
            "adminpanel.email.status" => "Status",
            "adminpanel.email.actions" => "Actions",
            "adminpanel.email.active" => "Active",
            "adminpanel.email.inactive" => "Inactive",
            "adminpanel.email.edit" => "Edit",
            "adminpanel.email.delete" => "Delete",
            "adminpanel.email.add_email_template" => "Add Email Template",
            "adminpanel.email.create_template" => "Create Template",
            "adminpanel.email.fill_all_languages" => "Please fill subject and body for all languages.",
            "adminpanel.email.failed_create_template" => "Failed to create template",
            "adminpanel.email.confirm_delete_template" => "Are you sure you want to delete this template?",
            "adminpanel.email.failed_delete_template" => "Failed to delete template",

            "adminpanel.car.current_km" => "Current KM",
            "adminpanel.car.status" => "CarGroup Status",
            "adminpanel.car.select_group" => "Select CarGroup Group",
            "adminpanel.car.available" => "Müsait",
            "adminpanel.car.rented" => "Kirada",
            "adminpanel.car.unavailable" => "Müsait Değil",

            "adminpanel.cars.filter.filter_label" => "Label for filter section",
            "adminpanel.cars.filter.filter_tip" => "Tooltip text for filter functionality",
            "adminpanel.cars.filter.car_filter" => "Heading for car filter section",
            "adminpanel.cars.filter.brand" => "Label for brand filter",
            "adminpanel.cars.filter.segment" => "Label for segment filter in admin",
            "adminpanel.cars.filter.trunk_capacity" => "Label for trunk capacity filter",
            "adminpanel.cars.filter.transmission_type" => "Label for transmission type filter",
            "adminpanel.cars.filter.body_type" => "Label for body type filter in admin",
            "adminpanel.cars.filter.fuel_type" => "Label for fuel type filter in admin",
            "adminpanel.cars.filter.button.filter" => "Label for filter button",
            "adminpanel.cars.filter.price_range" => "Label filter price range",

            "adminpanel.car.list.license_plate" => "Label for license plate input",
            "adminpanel.car.list.brand" => "Label for brand input",
            "adminpanel.car.list.model" => "Label for model input",
            "adminpanel.car.list.year" => "Label for year input",
            "adminpanel.car.list.seat_count" => "Label for seat count input",
            "adminpanel.car.list.trunk_capacity" => "Label for trunk capacity input",
            "adminpanel.car.list.segment" => "Label for segment input",
            "adminpanel.car.list.body_type" => "Label for body type input",
            "adminpanel.car.list.fuel_type" => "Label for fuel type input",
            "adminpanel.car.list.transmission_type" => "Label for transmission type input",
            "adminpanel.car.list.count" => "Label for car count",
            "adminpanel.car.list.releted_car_group" => "Araç Grubu",
            "adminpanel.car.list.current_locations" => "Güncel Lokasyon",


            "adminpanel.car.car_modify.operations" => "Heading for car modification operations",
            "adminpanel.car.car_modify.edit_price_information.edit_price_information" => "Heading for price information editing",
            "adminpanel.car.car_modify.edit_price_information.deposit" => "Label for deposit amount field",
            "adminpanel.car.car_modify.edit_price_information.deopsit_currency" => "Label for deposit currency field",
            "adminpanel.car.car_modify.edit_price_information.daily_price" => "Label for daily price field",
            "adminpanel.car.car_modify.edit_price_information.daily_price_currency" => "Label for daily price currency",
            /*"adminpanel.car.car_modify.edit_price_information.save" => "Text for save button in price editing",*/
            "adminpanel.car.car_modify.edit_car_information.edit_car_information" => "Heading for car information editing",
            "adminpanel.car.car_modify.edit_car_information.license_plate" => "Label for license plate field",
            "adminpanel.car.car_modify.edit_car_information.brand" => "Label for brand field",
            "adminpanel.car.car_modify.edit_car_information.model" => "Label for model field",
            "adminpanel.car.car_modify.edit_car_information.year" => "Label for year field",
            "adminpanel.car.car_modify.edit_car_information.seat_count" => "Label for seat count field",
            "adminpanel.car.car_modify.edit_car_information.trunk_capacity" => "Label for trunk capacity field",
            "adminpanel.car.car_modify.edit_car_information.segment" => "Label for segment field in editing",
            "adminpanel.car.car_modify.edit_car_information.body_type" => "Label for body type field in editing",
            "adminpanel.car.car_modify.edit_car_information.fuel_type" => "Label for fuel type field in editing",
            "adminpanel.car.car_modify.edit_car_information.transmission_type" => "Label for transmission type field",
            "adminpanel.car.car_modify.save" => "Text for save button in car info editing",
            "adminpanel.car.car_modify.edit_photos.edito_photos" => "Heading for photo editing section",
            "adminpanel.car.car_modify.edit_photos.click_for_add_photo" => "Prompt text for adding photos",
            "adminpanel.car.car_modify.edit_photos.empty" => "empty photos",
            "adminpanel.car.car_modify.edit_photos.cover" => "cover photo",
            "adminpanel.car.car_modify.edit_photos.max_{count}_photos_added" => "added {count} photos",
            "adminpanel.car.car_modify.edit_photos.cover_photo" => "Label for cover photo selection",
            /*"adminpanel.car.car_modify.edit_photos.save" => "Text for save button in photo editing",*/
            "adminpanel.car.car_modify.delete" => "Text for delete button/option",

            "adminpanel.car_group.add_car_group" => "Add CarGroup Group",
            "adminpanel.car_group.name" => "CarGroup Group Name",
            "adminpanel.car_group" => "Araç Grubu",
            "adminpanel.car_group.create_group" => "CarGroup Group Create",

            "adminpanel.add_car.add_car" => "Heading for add car page",
            "adminpanel.add_car.edit_car_information" => "Heading for car information section",
            "adminpanel.add_car.select_car_group" => "Select CarGroup Group",
            "adminpanel.add_car.license_plate" => "Label for license plate input",
            "adminpanel.add_car.select_location" => "Select location",
            "adminpanel.add_car.brand" => "Label for brand input",
            "adminpanel.add_car.model" => "Label for model input",
            "adminpanel.add_car.year" => "Label for year input",
            "adminpanel.add_car.seat_count" => "Label for seat count input",
            "adminpanel.add_car.trunk_capacity" => "Label for trunk capacity input",
            "adminpanel.add_car.segment" => "Label for segment input",
            "adminpanel.add_car.body_type" => "Label for body type input",
            "adminpanel.add_car.fuel_type" => "Label for fuel type input",
            "adminpanel.add_car.transmission_type" => "Label for transmission type input",
            "adminpanel.add_car.deposit_currency" => "Label for deposit currency selection",
            "adminpanel.add_car.deposit" => "Label for deposit amount input",
            "adminpanel.add_car.daily_price" => "Label for daily price input",
            "adminpanel.add_car.daily_price_currency" => "Label for daily price currency selection",
            "adminpanel.add_car.click_for_add_photo" => "Prompt text for adding photos",
            "adminpanel.add_car.cover" => "Label for cover photo selection",
            "adminpanel.add_car.save" => "Text for save button",

            "adminpanel.reservation.reservations" => "Heading for reservations page",
            "adminpanel.reservation.filter.filer" => "Label for filter section",
            "adminpanel.reservation.filter.filter_tip" => "Tooltip text for filtering",
            "adminpanel.reservation.filter.sort.sort_label" => "Label for sort dropdown",
            "adminpanel.reservation.filter.sort.suggested" => "suggested sort",
            "adminpanel.reservation.filter.sort.increase_based_price" => "increasing based price sort",
            "adminpanel.reservation.filter.sort.decrease_based_price" => "decrease based price sort",
            "adminpanel.reservation.filter.sort.latest" => "latest sort",
            "adminpanel.reservation.filter.sort.newest" => "newset sort",
            "adminpanel.reservation.filter.status" => "Label for status filter",
            "adminpanel.reservation.filter.recommended" => "Label for recommended filter",
            "adminpanel.reservation.filter.price_based_increase" => "Option for price ascending sort",
            "adminpanel.reservation.filter.price_based_decrease" => "Option for price descending sort",
            "adminpanel.reservation.filter.date_based_latest" => "Option for newest first sort",
            "adminpanel.reservation.filter.date_based_oldest" => "Option for oldest first sort",
            "adminpanel.reservation.filter.active" => "Filter option for active reservations",
            "adminpanel.reservation.filter.pending" => "Filter option for pending reservations",
            "adminpanel.reservation.filter.cancel" => "Filter option for cancelled reservations",
            "adminpanel.reservation.filter.copmleted" => "Filter option for completed reservations",
            "adminpanel.reservation.click_to_view_details_and_proceed_with_the_transaction" => "Instruction text for reservation actions",
            "adminpanel.reservation.page" => "Label for pagination",
            "adminpanel.reservation.name_and_surname" => "Column header for customer name",
            /*"adminpanel.reservation.surname" => "Column header for customer surname",*/
            "adminpanel.reservation.pick_up_date" => "Column header for pickup date",
            "adminpanel.reservation.return_date" => "Column header for return date",
            "adminpanel.reservation.payment_status" => "Column header for payment status",
            "adminpanel.reservation.status" => "Column header for reservation status",
            "adminpanel.reservation.reservation_modal.reservation_detail" => "Modal title for reservation details",
            "adminpanel.reservation.reservation_modal.name" => "Label for customer name in modal",
            "adminpanel.reservation.reservation_modal.surname" => "Label for customer surname in modal",
            "adminpanel.reservation.reservation_modal.phone_number" => "Label for phone number in modal",
            "adminpanel.reservation.reservation_modal.email" => "Label for email in modal",
            "adminpanel.reservation.reservation_modal.pick_up_date" => "Label for pickup date in modal",
            "adminpanel.reservation.reservation_modal.pick_up_location" => "Label for pickup location in modal",
            "adminpanel.reservation.reservation_modal.return_date" => "Label for return date in modal",
            "adminpanel.reservation.reservation_modal.return_location" => "Label for return location in modal",
            "adminpanel.reservation.reservation_modal.extra_price" => "Label for extra services price",
            "adminpanel.reservation.reservation_modal.total_price" => "Label for total price",
            "adminpanel.reservation.reservation_modal.payment_method" => "Label for payment method",
            "adminpanel.reservation.reservation_modal.payment_status" => "Label for payment status in modal",
            "adminpanel.reservation.reservation_modal.taken_extra_services" => "Label for extra services list",
            "adminpanel.reservation.reservation_modal.address" => "Addres bilgisi",

            "adminpanel.pricing.drop_price.drop_price" => "Heading for dynamic pricing section",
            "adminpanel.pricing.drop_price.vehicle_segment_coefficient.vehicle_segment_coefficient" => "Heading for segment coefficients",
            "adminpanel.pricing.drop_price.locations_price.your_purchase_history_is_reset_every_time_you_renew" => "Disclaimer text for pricing reset",
            "adminpanel.pricing.drop_price.locations_price.pick_up_location" => "Label for location in pricing",
            "adminpanel.pricing.drop_price.locations_price.currency" => "Label for currency selection",
            "adminpanel.pricing.drop_price.locations_price.save" => "Text for save button",

            "adminpanel.pricing.discounts.discounts" => "Heading for discounts section",
            "adminpanel.pricing.discounts.filter.sort.sort" => "Label for sort dropdown",
            "adminpanel.pricing.discounts.filter.sort.newest_based_on_start_date" => "Sort option by newest start date",
            "adminpanel.pricing.discounts.filter.sort.oldest_based_on_start_date" => "Sort option by oldest start date",
            "adminpanel.pricing.discounts.filter.status.status" => "Label for status filter",
            "adminpanel.pricing.discounts.filter.status.all_options" => "Option to show all statuses",
            "adminpanel.pricing.discounts.filter.status.active" => "Filter option for active discounts",
            "adminpanel.pricing.discounts.filter.status.passed" => "Filter option for expired discounts",
            "adminpanel.pricing.discounts.discount_type" => "Column header for discount type",
            "adminpanel.pricing.discounts.effected_vehicles_or_vehicle" => "Column header for affected vehicles",
            "adminpanel.pricing.discounts.discount_type_or_percentage" => "Column header for discount value",
            "adminpanel.pricing.discounts.start_date" => "Column header for start date",
            "adminpanel.pricing.discounts.end_date" => "Column header for end date",
            "adminpanel.pricing.discounts.status" => "Column header for discount status",
            "adminpanel.pricing.discounts.add_new" => "button for add new discount",

            "adminpanel.pricing.add_discount.add_discount" => "Heading for add discount page",
            "adminpanel.pricing.add_discount.discount_options" => "Heading for discount options",
            "adminpanel.pricing.add_discount.segment_based" => "Option for segment-based discount",
            "adminpanel.pricing.add_discount.car_based" => "Option for car-specific discount",
            "adminpanel.pricing.add_discount.all_vehicle_based" => "Option for all-vehicles discount",
            "adminpanel.pricing.add_discount.choose_a_segment" => "Prompt for segment selection",
            /*"adminpanel.pricing.add_discount.choose" => "Generic selection prompt",*/
            "adminpanel.pricing.add_discount.day_based_discount" => "Label for day-based discount",
            "adminpanel.pricing.add_discount.min_days" => "Label for minimum days input",
            "adminpanel.pricing.add_discount.max_days" => "Label for maximum days input",
            "adminpanel.pricing.add_discount.discount_type" => "Label for discount type selection",
            "adminpanel.pricing.add_discount.currency" => "Label for currency selection",
            "adminpanel.pricing.add_discount.discount_amount" => "Label for discount amount input",
            "adminpanel.pricing.add_discount.delete" => "Text for delete button",
            "adminpanel.pricing.add_discount.add_new" => "Text for add new button",
            "adminpanel.pricing.add_discount.save" => "Text for save button",

            "adminpanel.pricing.adding_services.internal_services.internal_services" => "Heading for internal services",
            "adminpanel.pricing.adding_services.internal_services.operations" => "Heading for operations section",
            "adminpanel.pricing.adding_services.internal_services.add_new_services" => "Heading for adding new services",
            "adminpanel.pricing.adding_services.internal_services.select_language" => "Label for language selection",
            "adminpanel.pricing.adding_services.internal_services.enter_a_new_service" => "Label for new service name input",
            "adminpanel.pricing.adding_services.internal_services.enter_a_new_service_description" => "Label for service description input",
            "adminpanel.pricing.adding_services.internal_services.save" => "Text for save button",

            "adminpanel.pricing.adding_services.external_services.external_services" => "Heading for external services",
            "adminpanel.pricing.adding_services.external_services.service" => "Column header for service name",
            "adminpanel.pricing.adding_services.external_services.1-3_days_price" => "Column header for 1-3 days price",
            "adminpanel.pricing.adding_services.external_services.4-7_days_price" => "Column header for 4-7 days price",
            "adminpanel.pricing.adding_services.external_services.8-15_days_price" => "Column header for 8-15 days price",
            "adminpanel.pricing.adding_services.external_services.more_than_15_days_price" => "Column header for 15+ days price",
            "adminpanel.pricing.adding_services.external_services.stock" => "Column header for stock status",
            "adminpanel.pricing.adding_services.external_services.max_limit" => "Column header for maximum limit",
            "adminpanel.pricing.adding_services.external_services.current_stock" => "Column header for current stock",
            "adminpanel.pricing.adding_services.external_services.description" => "Column header for service description",
            "adminpanel.pricing.adding_services.external_services.button.add_new_service" => "Button text for adding new service",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.add_new_service_label" => "text for adding new service heading",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.update_service_label" => "text for update service heading",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.select_language" => "Label for language selection in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.service_name" => "Label for service name input in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.service_description" => "Label for service description in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.currency" => "Label for currency selection in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.1-3_days_price" => "Label for 1-3 days price in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.4-7_days_price" => "Label for 4-7 days price in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.8-15_days_price" => "Label for 8-15 days price in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.more_than_15_days_price" => "Label for 15+ days price in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.stock" => "Label for stock input in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.max_limit" => "Label for maximum limit input in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.cancel" => "Text for cancel button in modal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.save" => "Text for save button in modal",
            "adminpanel.pricing.adding_services.external_services.update_service_modal.save" => "Text for save button in modal",

            "adminpanel.pricing.add_campaign.add_campaign" => "Heading for add campaign page",
            "adminpanel.pricing.add_campaign.select_language" => "Heading for add campaign page",
            "adminpanel.pricing.add_campaign.campaign_title" => "Label for campaign title input",
            "adminpanel.pricing.add_campaign.enter_a_campaign_title" => "Placeholder for campaign title",
            "adminpanel.pricing.add_campaign.campaign_cover_photo" => "Label for cover photo upload",
            "adminpanel.pricing.add_campaign.add_photo" => "Text for add photo button",
            "adminpanel.pricing.add_campaign.campaign_content" => "Label for campaign content",
            "adminpanel.pricing.add_campaign.button.add_a_discount" => "Text for adding discount button",
            "adminpanel.pricing.add_campaign.button.cancel_a_discount" => "Text for adding discount button",
            "adminpanel.pricing.add_campaign.select_start_date" => "Label for start date picker",
            "adminpanel.pricing.add_campaign.select_finish_date" => "Label for end date picker",
            "adminpanel.pricing.add_campaign.button.save" => "Text for add campaign button",
            "adminpanel.pricing.update_campaign.button.save" => "Text for update campaign button",

            "adminpanel.languages.languages" => "Languages header",
            "adminpanel.languages.language_id" => "id for language",
            "adminpanel.languages.language_name" => "language's name",
            "adminpanel.languages.language_code" => "language's code",
            "adminpanel.languages.status" => "languages'status",
            "adminpanel.languages.add_new" => "Add new language",

            "adminpanel.add_languages.add_language" => "Add language header",
            "adminpanel.add_languages.language_name" => "language's name",
            "adminpanel.add_languages.language_code" => "language's code",
            "adminpanel.add_languages.language_flag" => "language's flag",
            "adminpanel.add_languages.button.save" => "language save",
            "adminpanel.add_languages.input.search" => "language key search",
            "adminpanel.add_languages.apply_all" => "language key apply all",

            "adminpanel.languages.edit_language.language_information" => "Language information",
            "adminpanel.languages.edit_language.site_variables" => "Seciton variables header",
            "adminpanel.languages.edit_language.related_campaigns" => "Related Campaigns",
            "adminpanel.languages.edit_language.cars" => "CarGroups languages",
            "adminpanel.languages.edit_language.button.active" => "Active language",
            "adminpanel.languages.edit_language.button.deactive" => "Deactive language",
            "adminpanel.languages.edit_language.button.delete" => "Delete language",

            "adminpanel.segments.segments" => "Segments header",
            "adminpanel.segments.segment_id" => "Segment id",
            "adminpanel.segments.segment_name" => "Segment name",
            "adminpanel.segments.status" => "Segment status",
            "adminpanel.segments.status.active" => "Segment status active",
            "adminpanel.segments.status.pasive" => "Segment status pasive",
            "adminpanel.segments.button.add_new" => "Add new segment",

            "adminpanel.segments.add_segment.add_segment" => "Add new segment",
            "adminpanel.segments.add_segment.select_language" => "Select language header",
            "adminpanel.segments.add_segment.segment_name" => "Segment name",
            "adminpanel.segments.add_segment.segment_coefficient" => "Segment coefficient",
            "adminpanel.segments.add_segment.button.save" => "button label for Add segment",
            "adminpanel.segments.add_segment.you_can_enter_only_number" => "You can enter only number",
            "adminpanel.segments.add_segments.number_must_be_greater_zero" => "Number must be greater than zero",

            "adminpanel.body_types.body_types" => "Body types header",
            "adminpanel.body_types.body_type_id" => "Body Type ID",
            "adminpanel.body_types.body_types_name" => "Body Type Name",
            "adminpanel.body_types.status" => "Body Type status",
            "adminpanel.body_types.status.active" => "Body Types status active",
            "adminpanel.body_types.status.pasive" => "Body Types status pasive",
            "adminpanel.body_types.button.add_new" => "Add new body type",

            "adminpanel.add_body_type.add_body_type" => "Add new body type",
            "adminpanel.add_body_type.select_language" => "Select language header",
            "adminpanel.add_body_type.body_type_name" => "body type name",
            "adminpanel.add_body_type.button.save" => "button label for Add body type",

            "adminpanel.fuels.fuels" => "Fuels header",
            "adminpanel.fuels.fuel_id" => "Fuels ID",
            "adminpanel.fuels.fuel_name" => "Fuels Name",
            "adminpanel.fuels.status" => "Fuels status",
            "adminpanel.fuels.status.active" => "Fuels status active",
            "adminpanel.fuels.status.pasive" => "Fuels status pasive",
            "adminpanel.fuels.button.add_new" => "Add new fuels",

            "adminpanel.add_fuel.add_fuel" => "Add new fuel",
            "adminpanel.add_fuel.select_language" => "Select language header",
            "adminpanel.add_fuel.fuel_name" => "fuel name",
            "adminpanel.add_fuel.button.save" => "button label for Add fuel",

            "adminpanel.transmissions.transmissions" => "Transmissions header",
            "adminpanel.transmissions.transmission_id" => "Transmission ID",
            "adminpanel.transmissions.transmission_name" => "Transmission Name",
            "adminpanel.transmissions.status" => " Transmission Status header",
            "adminpanel.transmissions.status.active" => "Transmission Status active",
            "adminpanel.transmissions.status.pasive" => "Transmission Status pasive",
            "adminpanel.transmissions.button.add_new" => "Add new transmission",

            "adminpanel.add_transmission.add_transmission" => "Add new transmission",
            "adminpanel.add_transmission.select_language" => "Transmission language header",
            "adminpanel.add_transmission.transmission_name" => "Trabsmission name",
            "adminpanel.add_transmission.button.save" => "save button for add new Trabsmission",

            "adminpanel.update_segment.update_segment" => "Update segment",
            "adminpanel.update_segment.button.save" => "Update segment",

            "adminpanel.update_transmission.update_transmission" => "Update transmission",
            "adminpanem.update_transmission.button.save" => "save buutton for update transmission",

            "address.cars" => "CarGroups url",
            "address.car_groups" => "arac-gruplari",
            "address.locations" => "Locations url",
            "address.campaigns" => "Campaigns url",
            "address.car_porte_car_rental" => "Carporate Rental url",
            "address.about" => "About url",
            "address.blog" => "Blog url",
            "address.auth" => "Auth url",
            "address.searchReservations" => "Search Reservations url",
            "address.adminpanel" => "Admin Panel url",
            "address.reservations" => "Reservations url",
            "address.users" => "Users url",
            "address.drop-price" => "Drop Price url",
            "address.discounts" => "Discounts url",
            "address.internal-services" => "Internal services url",
            "address.external-services" => "External Services url",
            "address.languages" => "Languages url",
            "address.segments" => "Segments url",
            "address.body_types" => "BodyTypes url",
            "address.fuels" => "Fuels url",
            "address.transmissions" => "Transmissions url",
            "address.add" => "label for Add in url",
            "address.reservation-create" => "Reservation Create URL",
            "address.checkReservation" => "Check reservation url",
            "address.email-templates" => "Email Templates url",
            "address.website_settings" => "settings for website url",
            "address.page_settings" => "page settings url",
            "address.about_us" => "about page settings url",
            "address.blog_page" => "blog page settings url",
            "address.navigation_bar_settings" => "navigation bar settings url",

            "website.check_reservation.title" => "Check Reservation Title",
            "website.check_reservation.email_label" => "Email label for check reservation",
            "website.check_reservation.email_placeholder" => "Placeholder for email input",
            "website.check_reservation.id_label" => "Reservation ID label",
            "website.check_reservation.id_placeholder" => "Placeholder for reservation ID",
            "website.check_reservation.button_check" => "Check reservation button",
            "website.check_reservation.button_checking" => "Checking button state",

            "website.reservation_details.title" => "Reservation Details Title",
            "website.reservation_details.created_on" => "Created on date text",
            "website.reservation_details.back_to_search" => "Back to search link",
            "website.reservation_details.status.pending" => "Pending status",
            "website.reservation_details.status.confirmed" => "Confirmed status",
            "website.reservation_details.status.cancelled" => "Cancelled status",
            "website.reservation_details.status.completed" => "Completed status",
            "website.reservation_details.pickup" => "Pickup label",
            "website.reservation_details.return" => "Return label",
            "website.reservation_details.payment" => "Payment label",
            "website.reservation_details.total_price" => "Total Price label",
            "website.reservation_details.method" => "Method label",
            "website.reservation_details.payment_status" => "Payment Status label",
            "website.reservation_details.duration" => "Duration label",
            "website.reservation_details.days" => "Days text",
            "website.reservation_details.customer_info" => "Customer Info Header",
            "website.reservation_details.full_name" => "Full Name label",
            "website.reservation_details.email" => "Email label",
            "website.reservation_details.phone" => "Phone label",
            "website.reservation_details.cancel_button" => "Cancel button",
            "website.reservation_details.cancelling" => "Cancelling state",
            "website.reservation_details.cancelled_alert" => "Cancelled alert message",
            "website.reservation_details.confirm_cancel" => "Cancel confirmation message",

        ];
        protected $values = [
            "website.navigator.home" => "Ana Sayfa",
            "website.navigator.cars" => "Araçlar",
            "website.navigator.locations" => "Lokasyonlar",
            "website.navigator.campaigns" => "Kampanyalar",
            "website.navigator.car_porte_car_rental" => "CarGroup Porte Kiralama",
            "website.navigator.about_us" => "Hakkımızda",
            "website.navigator.check_reservation" => "Rezervasyon Kontrolü",
            "website.navigator.blog" => "Blog",

            "website.car_card.properties.properties_label" => "Özellikler",
            "website.car_card.properties.seat_count_{count}" => "{{count}} koltuk",
            "website.car_card.properties.trunk_capacity_{trunk_capacity}" => "{{trunk_capacity}} bagaj hacmi",
            "website.car_card.requirements.requirements_label" => "Gereksinimler",
            "website.car_card.requirements.required_min_{age}" => "Minimum {{age}} yaş",
            "website.car_card.requirements.{year}_year_experience" => "{{year}} yıl deneyim",
            "website.car_card.requirement.{amount}_{currency}_deposit" => "{{amount}} {{currency}} depozito",

            "website.car.transmission_type" => "Vites Türü",
            "website.car.fuel_type" => "Yakıt Türü",
            "website.car.segment" => "Segment",
            "website.car.body_type" => "Kasa Tipi",
            "website.car.trunk_capacity" => "Bagaj Hacmi",
            "website.car.seat_count" => "Koltuk Sayısı",
            "website.car.car_properties" => "Araç Özellikleri",
            "website.car.requirement.deposit" => "Depozito",
            "website.car.requirement.experience" => "Deneyim",
            "website.car.requirements.requirements_label" => "Gereksinimler",
            "website.car.requirements.required_min_age" => "Minimum yaş",
            "website.car.requirements.experience" => "Deneyim",
            "website.car.requirements.deposit" => "Depozito",
            "website.car.services_included_for_this_vehicle" => "Bu araç için dahil hizmetler",
            "website.car.options_and_extras" => "Opsiyonlar ve Ekstralar",

            "website.searchReservation.filter.sort.sort_label" => "Sırala",
            "website.searchReservation.filter.sort.price_increase" => "Fiyat (Artan)",
            "website.searchReservation.filter.sort.price_decrease" => "Fiyat (Azalan)",
            "website.searchReservation.filter.fuel_type_label" => "Yakıt Türü",
            "website.searchReservation.filter.segments_label" => "Segment",
            "website.searchReservation.filter.transmission_type_label" => "Vites Türü",
            "website.searchReservation.rent_now" => "Hemen Kirala",

            "website.auth.login.login_label" => "Giriş Yap",
            "website.auth.login.email_label" => "E-posta",
            "website.auth.login.invalid_email" => "Geçersiz e-posta formatı",
            "website.auth.login.password_label" => "Şifre",
            "website.auth.login.he_password_must_be_at_least_6_characters_long" => "Şifre en az 6 karakter olmalıdır",
            "website.auth.login.button.save" => "Giriş Yap",

            "website.auth.signup.name" => "Ad",
            "website.auth.signup.surname" => "Soyad",
            "website.auth.signup.email" => "E-posta",
            "website.auth.signup.birthday" => "Doğum Tarihi",
            "website.auth.signup.phone_number" => "Telefon Numarası",
            "website.auth.signup.identity_number" => "TC Kimlik No",
            "website.auth.signup.password" => "Şifre",
            "website.auth.signup.password_confirmation" => "Şifre Tekrar",
            "website.auth.signup.this_area_cannot_be_empty" => "Bu alan boş bırakılamaz",
            "website.auth.signup.passwords_do_not_match" => "Şifreler uyuşmuyor",
            "website.auth.signup.you_can_enter_only_number" => "Sadece numara girebilirsiniz",
            "website.auth.signup.invalid_email" => "Geçersiz e-posta",
            "website.auth.signup.he_password_must_be_at_least_6_characters_long" => "Şifre en az 6 karakter olmalıdır",
            "website.auth.signup.signup_label" => "Kayıt Ol",
            "website.auth.signup.button.save" => "Kayıt Ol",

            "website.home.pick_up_location" => "Alış Lokasyonu",
            "website.home.return_location" => "Teslim Lokasyonu",
            "website.home.pick_up_date_and_time" => "Alış Tarih ve Saati",
            "website.home.return_date_and_time" => "Teslim Tarih ve Saati",
            "website.home.button.save" => "Ara",

            "adminpanel.navigator.home" => "Yönetim Paneli",
            "adminpanel.navigator.vehicle" => "Araç",
            "adminpanel.navigator.vehicles" => "Araçlar",
            "adminpanel.navigator.add_vehicles" => "Araç Ekle",
            "adminpanel.navigator.reservation" => "Rezervasyon",
            "adminpanel.navigator.reservations" => "Rezervasyonlar",
            "adminpanel.navigator.pricing" => "Fiyatlandırma",
            "adminpanel.navigator.drop_price" => "Dinamik Fiyat",
            "adminpanel.navigator.discounts" => "İndirimler",
            "adminpanel.navigator.add_discount" => "İndirim Ekle",
            "adminpanel.navigator.extra_services" => "Ek Hizmetler",
            "adminpanel.navigator.internal_services" => "Dahili Hizmetler",
            "adminpanel.navigator.external_services" => "Harici Hizmetler",
            "adminpanel.navigator.campaigns" => "Kampanyalar",
            "adminpanel.navigator.add_campaign" => "Kampanya Ekle",
            "adminpanel.navigator.locations" => "Lokasyonlar",
            "adminpanel.navigator.users" => "Kullanıcılar",
            "adminpanel.navigator.language_operations" => "Dil İşlemleri",
            "adminpanel.navigator.add_language" => "Dil Ekle",
            "adminpanel.navigator.car_properties" => "Araç Özellikleri",
            "adminpanel.navigator.segments" => "Segmentler",
            "adminpanel.navigator.add_segment" => "Segment Ekle",
            "adminpanel.navigator.body_types" => "Araç Tipleri",
            "adminpanel.navigator.add_body_type" => "Araç Tipi Ekle",
            "adminpanel.navigator.fuels" => "Yakıt Tipleri",
            "adminpanel.navigator.add_fuel" => "Yakıt Tipi Ekle",
            "adminpanel.navigator.transmissions" => "Vites Tipleri",
            "adminpanel.navigator.add_transmission" => "Vites Tipi Ekle",
            "adminpanel.navigator.email_templates" => "E-posta Şablonları",
            "adminpanel.navigator.add_car_group" => "Araç Grubu Ekle",
            "adminpanel.navigator.car_groups" => "Araç Grubuları",
            "adminpanel.navigator.website" => "Website",
            "adminpanel.navigator.website_settings" => "Website Ayarları",
            "adminpanel.navigator.page_settings" => "Sayfa İşlemleri",
            "adminpanel.navigator.about_page" => "Hakkımızda Sayfası",
            "adminpanel.navigator.blog_page" => "Blog Sayfası",
            "adminpanel.navigator.blog_page_add" => "Blog Ekleme Sayfası",
            "adminpanel.navigator.navigation_bar_settings" => "Menü Ayarları",
            // Email Templates Turkish
            "adminpanel.email.edit_email_template" => "E-posta Şablonunu Düzenle",
            "adminpanel.email.back" => "Geri",
            "adminpanel.email.template_name" => "Şablon Adı",
            "adminpanel.email.template_name_placeholder" => "örn., password_reset",
            "adminpanel.email.subject" => "Konu",
            "adminpanel.email.email_subject_placeholder" => "E-posta konusu ({{değişkenler}} kullanabilirsiniz)",
            "adminpanel.email.email_subject_input" => "E-posta konusu",
            "adminpanel.email.body" => "İçerik",
            "adminpanel.email.email_body_placeholder" => "Dinamik içerik için {{değişken}} yer tutucuları kullanın.",
            "adminpanel.email.update_template" => "Şablonu Güncelle",
            "adminpanel.email.cancel" => "İptal",
            "adminpanel.email.email_templates" => "E-posta Şablonları",
            "adminpanel.email.add_template" => "Şablon Ekle",
            "adminpanel.email.search_templates" => "Şablon ara...",
            "adminpanel.email.name" => "Ad",
            "adminpanel.email.status" => "Durum",
            "adminpanel.email.actions" => "İşlemler",
            "adminpanel.email.active" => "Aktif",
            "adminpanel.email.inactive" => "Pasif",
            "adminpanel.email.edit" => "Düzenle",
            "adminpanel.email.delete" => "Sil",
            "adminpanel.email.add_email_template" => "E-posta Şablonu Ekle",
            "adminpanel.email.create_template" => "Şablon Oluştur",
            "adminpanel.email.fill_all_languages" => "Lütfen tüm diller için konu ve içerik doldurun.",
            "adminpanel.email.failed_create_template" => "Şablon oluşturulamadı",
            "adminpanel.email.confirm_delete_template" => "Bu şablonu silmek istediğinizden emin misiniz?",
            "adminpanel.email.failed_delete_template" => "Şablon silinemedi",

            "adminpanel.car.current_km" => "Güncel KM",
            "adminpanel.car.status" => "Durum",
            "adminpanel.car.select_group" => "Araç Grubu Seçiniz",
            "adminpanel.car.available" => "Müsait",
            "adminpanel.car.rented" => "Kirada",
            "adminpanel.car.unavailable" => "Müsait Değil",

            "adminpanel.cars.filter.filter_label" => "Filtrele",
            "adminpanel.cars.filter.filter_tip" => "Filtreleme seçenekleri",
            "adminpanel.cars.filter.car_filter" => "Araç Filtresi",
            "adminpanel.cars.filter.brand" => "Marka",
            "adminpanel.cars.filter.segment" => "Segment",
            "adminpanel.cars.filter.trunk_capacity" => "Bagaj Hacmi",
            "adminpanel.cars.filter.transmission_type" => "Vites Türü",
            "adminpanel.cars.filter.body_type" => "Kasa Tipi",
            "adminpanel.cars.filter.fuel_type" => "Yakıt Türü",
            "adminpanel.cars.filter.button.filter" => "Filtrele",
            "adminpanel.cars.filter.price_range" => "Fiyat Aralığı",

            "adminpanel.car.list.license_plate" => "Plaka",
            "adminpanel.car.list.brand" => "Marka",
            "adminpanel.car.list.model" => "Model",
            "adminpanel.car.list.year" => "Yıl",
            "adminpanel.car.list.seat_count" => "Koltuk Sayısı",
            "adminpanel.car.list.trunk_capacity" => "Bagaj Hacmi",
            "adminpanel.car.list.segment" => "Segment",
            "adminpanel.car.list.body_type" => "Kasa Tipi",
            "adminpanel.car.list.fuel_type" => "Yakıt Türü",
            "adminpanel.car.list.transmission_type" => "Vites Türü",
            "adminpanel.car.list.count" => "Araç Sayısı",
            "adminpanel.car.list.releted_car_group" => "Araç Grubu",
            "adminpanel.car.list.current_locations" => "Güncel Lokasyon",

            "adminpanel.car.car_modify.operations" => "İşlemler",
            "adminpanel.car.car_modify.edit_price_information.edit_price_information" => "Fiyat Bilgilerini Düzenle",
            "adminpanel.car.car_modify.edit_price_information.deposit" => "Depozito",
            "adminpanel.car.car_modify.edit_price_information.deopsit_currency" => "Depozito Para Birimi",
            "adminpanel.car.car_modify.edit_price_information.daily_price" => "Günlük Fiyat",
            "adminpanel.car.car_modify.edit_price_information.daily_price_currency" => "Günlük Fiyat Para Birimi",
            "adminpanel.car.car_modify.edit_car_information.edit_car_information" => "Araç Bilgilerini Düzenle",
            "adminpanel.car.car_modify.edit_car_information.license_plate" => "Plaka",
            "adminpanel.car.car_modify.edit_car_information.brand" => "Marka",
            "adminpanel.car.car_modify.edit_car_information.model" => "Model",
            "adminpanel.car.car_modify.edit_car_information.year" => "Yıl",
            "adminpanel.car.car_modify.edit_car_information.seat_count" => "Koltuk Sayısı",
            "adminpanel.car.car_modify.edit_car_information.trunk_capacity" => "Bagaj Hacmi",
            "adminpanel.car.car_modify.edit_car_information.segment" => "Segment",
            "adminpanel.car.car_modify.edit_car_information.body_type" => "Kasa Tipi",
            "adminpanel.car.car_modify.edit_car_information.fuel_type" => "Yakıt Türü",
            "adminpanel.car.car_modify.edit_car_information.transmission_type" => "Vites Türü",
            "adminpanel.car.car_modify.save" => "Kaydet",
            "adminpanel.car.car_modify.edit_photos.edito_photos" => "Fotoğrafları Düzenle",
            "adminpanel.car.car_modify.edit_photos.click_for_add_photo" => "Fotoğraf eklemek için tıklayın",
            "adminpanel.car.car_modify.edit_photos.empty" => "boş fotoğraflar",
            "adminpanel.car.car_modify.edit_photos.cover" => "kapak",
            "adminpanel.car.car_modify.edit_photos.max_{count}_photos_added" => "maksimum {{count}} fotoğraf eklendi",
            "adminpanel.car.car_modify.edit_photos.cover_photo" => "Kapak Fotoğrafı",
            "adminpanel.car.car_modify.delete" => "Sil",

            "adminpanel.car_group.add_car_group" => "Araç Grubu Ekle",
            "adminpanel.car_group.name" => "Araç Grubu İsmi",
            "adminpanel.car_group" => "Araç Grubu",
            "adminpanel.car_group.create_group" => "Grup Ekle",

            "adminpanel.add_car.add_car" => "Araç Ekle",
            "adminpanel.add_car.edit_car_information" => "Araç Bilgilerini Düzenle",
            "adminpanel.add_car.license_plate" => "Plaka",
            "adminpanel.add_car.select_car_group" => "Araç Grubu Seçiniz",
            "adminpanel.add_car.select_location" => "Lokasyon Seçiniz",
            "adminpanel.add_car.brand" => "Marka",
            "adminpanel.add_car.model" => "Model",
            "adminpanel.add_car.year" => "Yıl",
            "adminpanel.add_car.seat_count" => "Koltuk Sayısı",
            "adminpanel.add_car.trunk_capacity" => "Bagaj Hacmi",
            "adminpanel.add_car.segment" => "Segment",
            "adminpanel.add_car.body_type" => "Kasa Tipi",
            "adminpanel.add_car.fuel_type" => "Yakıt Türü",
            "adminpanel.add_car.transmission_type" => "Vites Türü",
            "adminpanel.add_car.deposit_currency" => "Depozito Para Birimi",
            "adminpanel.add_car.deposit" => "Depozito",
            "adminpanel.add_car.daily_price" => "Günlük Fiyat",
            "adminpanel.add_car.daily_price_currency" => "Günlük Fiyat Para Birimi",
            "adminpanel.add_car.click_for_add_photo" => "Fotoğraf eklemek için tıklayın",
            "adminpanel.add_car.cover" => "Kapak",
            "adminpanel.add_car.save" => "Kaydet",

            "adminpanel.reservation.reservations" => "Rezervasyonlar",
            "adminpanel.reservation.filter.filer" => "Filtre",
            "adminpanel.reservation.filter.filter_tip" => "Filtreleme ipuçları",
            "adminpanel.reservation.filter.sort.sort_label" => "Sırala",
            "adminpanel.reservation.filter.sort.suggested" => "Önerilen",
            "adminpanel.reservation.filter.sort.increase_based_price" => "Fiyata göre artan",
            "adminpanel.reservation.filter.sort.decrease_based_price" => "Fiyata göre azalan",
            "adminpanel.reservation.filter.sort.latest" => "En yeni",
            "adminpanel.reservation.filter.sort.newest" => "En yeni",
            "adminpanel.reservation.filter.status" => "Durum",
            "adminpanel.reservation.filter.recommended" => "Önerilen",
            "adminpanel.reservation.filter.price_based_increase" => "Fiyata göre artan",
            "adminpanel.reservation.filter.price_based_decrease" => "Fiyata göre azalan",
            "adminpanel.reservation.filter.date_based_latest" => "Tarihe göre en yeni",
            "adminpanel.reservation.filter.date_based_oldest" => "Tarihe göre en eski",
            "adminpanel.reservation.filter.active" => "Aktif",
            "adminpanel.reservation.filter.pending" => "Beklemede",
            "adminpanel.reservation.filter.cancel" => "İptal",
            "adminpanel.reservation.filter.copmleted" => "Tamamlandı",
            "adminpanel.reservation.click_to_view_details_and_proceed_with_the_transaction" => "Detayları görüntülemek ve işleme devam etmek için tıklayın",
            "adminpanel.reservation.page" => "Sayfa",
            "adminpanel.reservation.name_and_surname" => "Ad Soyad",
            "adminpanel.reservation.pick_up_date" => "Alış Tarihi",
            "adminpanel.reservation.return_date" => "Teslim Tarihi",
            "adminpanel.reservation.payment_status" => "Ödeme Durumu",
            "adminpanel.reservation.status" => "Durum",
            "adminpanel.reservation.reservation_modal.reservation_detail" => "Rezervasyon Detayı",
            "adminpanel.reservation.reservation_modal.name" => "Ad",
            "adminpanel.reservation.reservation_modal.surname" => "Soyad",
            "adminpanel.reservation.reservation_modal.phone_number" => "Telefon Numarası",
            "adminpanel.reservation.reservation_modal.email" => "E-posta",
            "adminpanel.reservation.reservation_modal.pick_up_date" => "Alış Tarihi",
            "adminpanel.reservation.reservation_modal.pick_up_location" => "Alış Lokasyonu",
            "adminpanel.reservation.reservation_modal.return_date" => "Teslim Tarihi",
            "adminpanel.reservation.reservation_modal.return_location" => "Teslim Lokasyonu",
            "adminpanel.reservation.reservation_modal.extra_price" => "Ekstra Ücret",
            "adminpanel.reservation.reservation_modal.total_price" => "Toplam Ücret",
            "adminpanel.reservation.reservation_modal.payment_method" => "Ödeme Yöntemi",
            "adminpanel.reservation.reservation_modal.payment_status" => "Ödeme Durumu",
            "adminpanel.reservation.reservation_modal.taken_extra_services" => "Alınan Ek Hizmetler",
            "adminpanel.reservation.reservation_modal.address" => "Adres",

            "adminpanel.pricing.drop_price.drop_price" => "Dinamik Fiyat",
            "adminpanel.pricing.drop_price.vehicle_segment_coefficient.vehicle_segment_coefficient" => "Araç Segment Katsayısı",
            "adminpanel.pricing.drop_price.locations_price.your_purchase_history_is_reset_every_time_you_renew" => "Fiyat geçmişiniz her yenilemede sıfırlanır",
            "adminpanel.pricing.drop_price.locations_price.pick_up_location" => "Alış Lokasyonu",
            "adminpanel.pricing.drop_price.locations_price.currency" => "Para Birimi",
            "adminpanel.pricing.drop_price.locations_price.save" => "Kaydet",

            "adminpanel.pricing.discounts.discounts" => "İndirimler",
            "adminpanel.pricing.discounts.filter.sort.sort" => "Sırala",
            "adminpanel.pricing.discounts.filter.sort.newest_based_on_start_date" => "Başlangıç tarihine göre en yeni",
            "adminpanel.pricing.discounts.filter.sort.oldest_based_on_start_date" => "Başlangıç tarihine göre en eski",
            "adminpanel.pricing.discounts.filter.status.status" => "Durum",
            "adminpanel.pricing.discounts.filter.status.all_options" => "Tüm Seçenekler",
            "adminpanel.pricing.discounts.filter.status.active" => "Aktif",
            "adminpanel.pricing.discounts.filter.status.passed" => "Geçmiş",
            "adminpanel.pricing.discounts.discount_type" => "İndirim Türü",
            "adminpanel.pricing.discounts.effected_vehicles_or_vehicle" => "Etkilenen Araç(lar)",
            "adminpanel.pricing.discounts.discount_type_or_percentage" => "İndirim Türü/Yüzdesi",
            "adminpanel.pricing.discounts.start_date" => "Başlangıç Tarihi",
            "adminpanel.pricing.discounts.end_date" => "Bitiş Tarihi",
            "adminpanel.pricing.discounts.status" => "Durum",
            "adminpanel.pricing.discounts.add_new" => "Yeni Ekle",

            "adminpanel.pricing.add_discount.add_discount" => "İndirim Ekle",
            "adminpanel.pricing.add_discount.discount_options" => "İndirim Seçenekleri",
            "adminpanel.pricing.add_discount.segment_based" => "Segment Bazlı",
            "adminpanel.pricing.add_discount.car_based" => "Araç Bazlı",
            "adminpanel.pricing.add_discount.all_vehicle_based" => "Tüm Araçlar Bazlı",
            "adminpanel.pricing.add_discount.choose_a_segment" => "Bir segment seçin",
            "adminpanel.pricing.add_discount.day_based_discount" => "Gün Bazlı İndirim",
            "adminpanel.pricing.add_discount.min_days" => "Minimum Gün",
            "adminpanel.pricing.add_discount.max_days" => "Maksimum Gün",
            "adminpanel.pricing.add_discount.discount_type" => "İndirim Türü",
            "adminpanel.pricing.add_discount.currency" => "Para Birimi",
            "adminpanel.pricing.add_discount.discount_amount" => "İndirim Miktarı",
            "adminpanel.pricing.add_discount.delete" => "Sil",
            "adminpanel.pricing.add_discount.add_new" => "Yeni Ekle",
            "adminpanel.pricing.add_discount.save" => "Kaydet",

            "adminpanel.pricing.adding_services.internal_services.internal_services" => "Dahili Hizmetler",
            "adminpanel.pricing.adding_services.internal_services.operations" => "İşlemler",
            "adminpanel.pricing.adding_services.internal_services.add_new_services" => "Yeni Hizmet Ekle",
            "adminpanel.pricing.adding_services.internal_services.select_language" => "Dil Seçin",
            "adminpanel.pricing.adding_services.internal_services.enter_a_new_service" => "Yeni hizmet adı girin",
            "adminpanel.pricing.adding_services.internal_services.enter_a_new_service_description" => "Yeni hizmet açıklaması girin",
            "adminpanel.pricing.adding_services.internal_services.save" => "Kaydet",

            "adminpanel.pricing.adding_services.external_services.external_services" => "Harici Hizmetler",
            "adminpanel.pricing.adding_services.external_services.service" => "Hizmet",
            "adminpanel.pricing.adding_services.external_services.1-3_days_price" => "1-3 Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.4-7_days_price" => "4-7 Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.8-15_days_price" => "8-15 Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.more_than_15_days_price" => "15+ Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.stock" => "Stok",
            "adminpanel.pricing.adding_services.external_services.max_limit" => "Maksimum Limit",
            "adminpanel.pricing.adding_services.external_services.current_stock" => "Mevcut Stok",
            "adminpanel.pricing.adding_services.external_services.description" => "Açıklama",
            "adminpanel.pricing.adding_services.external_services.button.add_new_service" => "Yeni Hizmet Ekle",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.add_new_service_label" => "Yeni Hizmet Ekle",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.update_service_label" => "Hizmet Güncelle",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.select_language" => "Dil Seçin",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.service_name" => "Hizmet Adı",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.service_description" => "Hizmet Açıklaması",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.currency" => "Para Birimi",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.1-3_days_price" => "1-3 Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.4-7_days_price" => "4-7 Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.8-15_days_price" => "8-15 Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.more_than_15_days_price" => "15+ Gün Fiyat",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.stock" => "Stok",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.max_limit" => "Maksimum Limit",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.cancel" => "İptal",
            "adminpanel.pricing.adding_services.external_services.add_new_service_modal.save" => "Kaydet",
            "adminpanel.pricing.adding_services.external_services.update_service_modal.save" => "Kaydet",

            "adminpanel.pricing.add_campaign.add_campaign" => "Kampanya Ekle",
            "adminpanel.pricing.add_campaign.select_language" => "Dil Seçin",
            "adminpanel.pricing.add_campaign.campaign_title" => "Kampanya Başlığı",
            "adminpanel.pricing.add_campaign.enter_a_campaign_title" => "Kampanya başlığı girin",
            "adminpanel.pricing.add_campaign.campaign_cover_photo" => "Kampanya Kapak Fotoğrafı",
            "adminpanel.pricing.add_campaign.add_photo" => "Fotoğraf Ekle",
            "adminpanel.pricing.add_campaign.campaign_content" => "Kampanya İçeriği",
            "adminpanel.pricing.add_campaign.button.add_a_discount" => "İndirim Ekle",
            "adminpanel.pricing.add_campaign.button.cancel_a_discount" => "İndirim İptal",
            "adminpanel.pricing.add_campaign.select_start_date" => "Başlangıç Tarihi Seçin",
            "adminpanel.pricing.add_campaign.select_finish_date" => "Bitiş Tarihi Seçin",
            "adminpanel.pricing.add_campaign.button.save" => "Kaydet",
            "adminpanel.pricing.update_campaign.button.save" => "Güncelle",

            "adminpanel.languages.languages" => "Diller",
            "adminpanel.languages.language_id" => "Dil ID",
            "adminpanel.languages.language_name" => "Dil Adı",
            "adminpanel.languages.language_code" => "Dil Kodu",
            "adminpanel.languages.status" => "Durum",
            "adminpanel.languages.add_new" => "Yeni Ekle",

            "adminpanel.add_languages.add_language" => "Dil Ekle",
            "adminpanel.add_languages.language_name" => "Dil Adı",
            "adminpanel.add_languages.language_code" => "Dil Kodu",
            "adminpanel.add_languages.language_flag" => "Dil Bayrağı",
            "adminpanel.add_languages.button.save" => "Kaydet",
            "adminpanel.add_languages.input.search" => "Anahtar kelime ara",
            "adminpanel.add_languages.apply_all" => "Tümüne uygula",

            "adminpanel.languages.edit_language.language_information" => "Dil Bilgisi",
            "adminpanel.languages.edit_language.site_variables" => "Seciton Değişkenleri",
            "adminpanel.languages.edit_language.related_campaigns" => "İlgili Kampanyalar",
            "adminpanel.languages.edit_language.cars" => "Araçlar",
            "adminpanel.languages.edit_language.button.active" => "Aktif Et",
            "adminpanel.languages.edit_language.button.deactive" => "Pasif Et",
            "adminpanel.languages.edit_language.button.delete" => "Sil",

            "adminpanel.segments.segments" => "Segmentler",
            "adminpanel.segments.segment_id" => "Segment ID",
            "adminpanel.segments.segment_name" => "Segment Adı",
            "adminpanel.segments.status" => "Segment Durumu",
            "adminpanel.segments.status.active" => "Aktif",
            "adminpanel.segments.status.pasive" => "Pasif",
            "adminpanel.segments.button.add_new" => "Yeni Segment Ekle",

            "adminpanel.segments.add_segment.add_segment" => "Yeni Segment Ekle",
            "adminpanel.segments.add_segment.select_language" => "Dil Seçiniz",
            "adminpanel.segments.add_segment.segment_name" => "Segment Adı",
            "adminpanel.segments.add_segment.segment_coefficient" => "Segment Katsayısı",
            "adminpanel.segments.add_segment.button.save" => "Ekle",
            "adminpanel.segments.add_segment.you_can_enter_only_number" => "Sadece Sayı Girebilirsiniz",
            "adminpanel.segments.add_segments.number_must_be_greater_zero" => "Sayı 0'dan Büyük Olmalı",

            "adminpanel.body_types.body_types" => "Araç Tipi",
            "adminpanel.body_types.body_type_id" => "Araç Tİpi ID",
            "adminpanel.body_types.body_types_name" => "Araç Tipi İsmi",
            "adminpanel.body_types.status" => "Araç Tİpi Durumu",
            "adminpanel.body_types.status.active" => "Aktif",
            "adminpanel.body_types.status.pasive" => "Pasif",
            "adminpanel.body_types.button.add_new" => "Yeni Araç Tipi Ekle",

            "adminpanel.add_body_type.add_body_type" => "Yeni Araç Tipi Ekle",
            "adminpanel.add_body_type.select_language" => "Dil Seçiniz",
            "adminpanel.add_body_type.body_type_name" => "Araç Tipi İsmi",
            "adminpanel.add_body_type.button.save" => "Araç Tipi Ekle",

            "adminpanel.fuels.fuels" => "Yakıtlar",
            "adminpanel.fuels.fuel_id" => "Yakıt ID",
            "adminpanel.fuels.fuel_name" => "Yakıt Name",
            "adminpanel.fuels.status" => "Durum",
            "adminpanel.fuels.status.active" => "Aktif",
            "adminpanel.fuels.status.pasive" => "Pasif",
            "adminpanel.fuels.button.add_new" => "Yeni Yakıt Ekle",

            "adminpanel.add_fuel.add_fuel" => "Yeni Yakıt Ekle",
            "adminpanel.add_fuel.select_language" => "Dil Seçiniz",
            "adminpanel.add_fuel.fuel_name" => "Yakıt Adı",
            "adminpanel.add_fuel.button.save" => "Yakıt Ekle",

            "adminpanel.transmissions.transmissions" => "Vitesler",
            "adminpanel.transmissions.transmission_id" => "Vites ID",
            "adminpanel.transmissions.transmission_name" => "Vites Name",
            "adminpanel.transmissions.status" => "Durum",
            "adminpanel.transmissions.status.active" => "Aktif",
            "adminpanel.transmissions.status.pasive" => "Pasif",
            "adminpanel.transmissions.button.add_new" => "Yeni Yakıt Ekle",

            "adminpanel.add_transmission.add_transmission" => "Yeni Vites Türü Ekle",
            "adminpanel.add_transmission.select_language" => "Dil Seçiniz",
            "adminpanel.add_transmission.transmission_name" => "Vites Türü Adı",
            "adminpanel.add_transmission.button.save" => "Vites Türü Ekle",

            "adminpanel.update_segment.update_segment" => "Segmenti GÜncelle",
            "adminpanel.update_segment.button.save" => "GÜncelle",

            "adminpanel.update_transmission.update_transmission" => "Vites Tipini Güncelle",
            "adminpanem.update_transmission.button.save" => "Güncelle",

            "address.cars" => "arabalar",
            "address.car_groups" => "arac-gruplari",
            "address.locations" => "lokasyonlar",
            "address.campaigns" => "kampanyalar",
            "address.car_porte_car_rental" => "kurumsal-arac-kiralamalar",
            "address.about" => "hakkimizda",
            "address.blog" => "blog",
            "address.auth" => "giris",
            "address.searchReservations" => "rezervasyon-ara",
            "address.adminpanel" => "adminpanel",
            "address.reservations" => "rezervasyonlar",
            "address.users" => "kullnicilar",
            "address.drop-price" => "birakim-ucreti",
            "address.discounts" => "indirimler",
            "address.internal-services" => "dahili-hizmetler",
            "address.external-services" => "harici-hizmetler",
            "address.languages" => "diller",
            "address.segments" => "segmentler",
            "address.body_types" => "arac-tipleri",
            "address.fuels" => "yakitlar",
            "address.transmissions" => "vites-tipleri",
            "address.add" => "ekle",
            "address.reservation-create" => "rezervasyon-ekle",
            "address.checkReservation" => "rezervasyon-kontrol",
            "address.email-templates" => "email-sablonlari",
            "address.website_settings" => "webiste-ayarlari",
            "address.page_settings" => "sayfa-ayarlari",
            "address.about_us" => "hakkimizda-sayfasi",
            "address.blog_page" => "blog-sayfasi",
            "address.navigation_bar_settings" => "menu-ayarları",

            "website.check_reservation.title" => "Rezervasyon Kontrolü",
            "website.check_reservation.email_label" => "E-posta Adresi",
            "website.check_reservation.email_placeholder" => "E-postanızı giriniz",
            "website.check_reservation.id_label" => "Rezervasyon ID",
            "website.check_reservation.id_placeholder" => "Rezervasyon ID'nizi giriniz",
            "website.check_reservation.button_check" => "Rezervasyonu Kontrol Et",
            "website.check_reservation.button_checking" => "Kontrol Ediliyor...",

            "website.reservation_details.title" => "Rezervasyon #{{id}}",
            "website.reservation_details.created_on" => "Oluşturulma Tarihi: {{date}}",
            "website.reservation_details.back_to_search" => "Aramaya Dön",
            "website.reservation_details.status.pending" => "Bekliyor",
            "website.reservation_details.status.confirmed" => "Onaylandı",
            "website.reservation_details.status.cancelled" => "İptal Edildi",
            "website.reservation_details.status.completed" => "Tamamlandı",
            "website.reservation_details.pickup" => "Alış",
            "website.reservation_details.return" => "İade",
            "website.reservation_details.payment" => "Ödeme",
            "website.reservation_details.total_price" => "Toplam Tutar:",
            "website.reservation_details.method" => "Yöntem:",
            "website.reservation_details.payment_status" => "Ödeme Durumu:",
            "website.reservation_details.duration" => "Süre",
            "website.reservation_details.days" => "Gün",
            "website.reservation_details.customer_info" => "Müşteri Bilgileri",
            "website.reservation_details.full_name" => "Ad Soyad",
            "website.reservation_details.email" => "E-posta",
            "website.reservation_details.phone" => "Telefon",
            "website.reservation_details.cancel_button" => "Rezervasyonu İptal Et",
            "website.reservation_details.cancelling" => "İptal Ediliyor...",
            "website.reservation_details.cancelled_alert" => "Bu rezervasyon iptal edilmiştir.",
            "website.reservation_details.confirm_cancel" => "Bu rezervasyonu iptal etmek istediğinizden emin misiniz?",

            "general.all" => "Hepsi",
            "general.active" => "Aktif",
            "general.passive" => "Pasif",
            "general.sort" => "Sırala",
        ];
        public function run(): void
        {
            try {
                $currencies = [
                    ['code' => 'EUR', 'symbol' => '€', 'exchange_rate' => 1, 'is_default' => true, 'is_active' => true],
                    ['code' => 'USD', 'symbol' => '$', 'exchange_rate' => 1/1.16, 'is_default' => false, 'is_active' => true],
                    ['code' => 'TRY', 'symbol' => '₺', 'exchange_rate' => 1/48, 'is_default' => false, 'is_active' => true],
                ];

                foreach ($currencies as $currency) {
                    Currency::updateOrCreate(
                        ['code' => $currency['code']],
                        $currency
                    );
                }
                $tr = Language::firstOrCreate(['code' => 'tr'], [
                    'name' => 'Türkçe',
                    'flag_photo_path' => 'svg/flags/tr.svg',
                ]);

                $en = Language::firstOrCreate(['code' => 'en'], [
                    'name' => 'English',
                    'flag_photo_path' => 'svg/flags/en.svg',
                ]);

                foreach ($this->keys as $key => $value) {
                    $translationKey = TranslationKey::firstOrCreate([
                        'key' => $key,
                    ], [
                        'description' => $value,
                    ]);

                    Translation::updateOrCreate([
                        'language_id' => $tr->id,
                        'translation_key_id' => $translationKey->id,
                    ], [
                        'value' => $this->values[$key],
                    ]);

                    $enValue = @json_decode(file_get_contents(
                        'https://translate.googleapis.com/translate_a/single?client=gtx&sl=tr&tl=en&dt=t&q=' . urlencode($this->values[$key])
                    ), true)[0][0][0] ?? '';



                    Translation::updateOrCreate([
                        'language_id' => $en->id,
                        'translation_key_id' => $translationKey->id,
                    ], [
                        'value' => $enValue,
                    ]);
                }

            } catch (\Exception $e) {
                $this->command->error('Seeder hatası: ' . $e->getMessage());
            }
        }

    }
